//! Proxmox VE API client. API-token auth only for the MVP — ticket/cookie
//! flow can be added later when a password-based caller appears.
//!
//! Token format follows Proxmox's documented header:
//!   Authorization: PVEAPIToken=USER@REALM!TOKENID=UUID
//!
//! The wire surface is the progenitor-generated `generated::Client` —
//! every hand-rolled HTTP method has been retired. Two endpoints still
//! need a raw-URL helper because the upstream schema models indexed
//! keys (`netN`, `mpN`) as a single `[n]` field that progenitor can't
//! materialize into separate keys:
//!   - `fetch_guest_config` — pulls the full guest config so callers
//!     can extract MACs / mount points off `netN` / `mpN`.
//!
//! Everything else routes through generated methods directly at the
//! call site.

pub mod abi_export;
pub mod cluster;
pub mod cluster_roster_impl;
pub mod containers_adapter;
pub mod responses;
pub mod tools;
pub mod topology;

/// Typed Proxmox VE client generated by `progenitor` from
/// `specs/proxmox.openapi.json` at build time. Refresh the spec via
/// `make proxmox-spec-refresh` after upstream API changes.
#[allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case
)]
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/proxmox_codegen.rs"));
}

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone)]
pub struct Config {
    pub base_url: String,
    /// `user@realm!tokenid` — the part before the `=` in the auth header.
    pub token_id: String,
    /// The UUID secret — the part after the `=`.
    pub token_secret: String,
    /// Skip TLS verification (homelab self-signed certs).
    pub insecure: bool,
}

impl Config {
    pub fn new(
        base_url: impl Into<String>,
        token_id: impl Into<String>,
        token_secret: impl Into<String>,
    ) -> Self {
        Self {
            base_url: base_url.into(),
            token_id: token_id.into(),
            token_secret: token_secret.into(),
            insecure: false,
        }
    }

    pub fn insecure(mut self, on: bool) -> Self {
        self.insecure = on;
        self
    }

    fn auth_header_value(&self) -> String {
        format!("PVEAPIToken={}={}", self.token_id, self.token_secret)
    }

    /// Build the underlying `reqwest::Client` with the PVE API-token
    /// header pre-attached and TLS verification toggled per `insecure`.
    /// The generated client gets this as its inner transport — so every
    /// generated method call carries auth without per-call wiring.
    pub fn build_reqwest_client(&self) -> Result<reqwest::Client, ProxmoxError> {
        plugin_toolkit::api_client::ApiClientBuilder::new()
            .header("authorization", self.auth_header_value())
            .and_then(|b| b.insecure(self.insecure).build())
            .map_err(|e| ProxmoxError::Malformed(format!("reqwest build: {e}")))
    }

    /// Build a generated `proxmox::generated::Client` ready to call
    /// every codegen'd method. Base URL is the API root
    /// (e.g. `https://host:8006/api2/json`).
    pub fn build_generated_client(&self) -> Result<generated::Client, ProxmoxError> {
        let http = self.build_reqwest_client()?;
        Ok(generated::Client::new_with_client(&self.base_url, http))
    }
}

#[derive(Debug, Error)]
pub enum ProxmoxError {
    #[error("missing required field: {0}")]
    Missing(&'static str),
    #[error("unsupported action '{0}' (expected start | stop | shutdown | reboot)")]
    BadAction(String),
    #[error("unsupported guest kind '{0}' (expected qemu | lxc)")]
    BadGuestKind(String),
    #[error("malformed proxmox response: {0}")]
    Malformed(String),
    #[error("proxmox transport: {0}")]
    Transport(String),
}

/// Allowed lifecycle actions on VMs and containers. Constraining the set up
/// front keeps callers from forwarding arbitrary strings to the Proxmox API.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum ProxmoxAction {
    Start,
    Stop,
    Shutdown,
    Reboot,
}

impl ProxmoxAction {
    pub fn as_str(self) -> &'static str {
        match self {
            ProxmoxAction::Start => "start",
            ProxmoxAction::Stop => "stop",
            ProxmoxAction::Shutdown => "shutdown",
            ProxmoxAction::Reboot => "reboot",
        }
    }
}

/// Guest kind — used by snapshot ops that work for both VMs and containers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GuestKind {
    Qemu,
    Lxc,
}

impl GuestKind {
    pub fn as_str(self) -> &'static str {
        match self {
            GuestKind::Qemu => "qemu",
            GuestKind::Lxc => "lxc",
        }
    }
}

impl std::str::FromStr for GuestKind {
    type Err = ProxmoxError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "qemu" | "vm" => Ok(GuestKind::Qemu),
            "lxc" | "container" => Ok(GuestKind::Lxc),
            other => Err(ProxmoxError::BadGuestKind(other.to_string())),
        }
    }
}

impl std::str::FromStr for ProxmoxAction {
    type Err = ProxmoxError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "start" => Ok(ProxmoxAction::Start),
            "stop" => Ok(ProxmoxAction::Stop),
            "shutdown" => Ok(ProxmoxAction::Shutdown),
            "reboot" => Ok(ProxmoxAction::Reboot),
            other => Err(ProxmoxError::BadAction(other.to_string())),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProxmoxActionResult {
    pub node: String,
    pub vmid: u64,
    pub action: String,
    /// Proxmox returns a UPID (Unique Process ID) for async tasks.
    pub upid: Option<String>,
    pub status: u16,
}

/// Pull a guest config (qemu or lxc) and parse it into the typed
/// `responses::GuestConfigResponse` shape so callers can walk
/// `netN` + `mpN` keys via the BTreeMap.
///
/// Why this exists outside the generated client: the upstream OpenAPI
/// schema models indexed config keys as `net[n]` / `mp[n]` placeholders,
/// so progenitor emits single fields (`net_n`, `mp_n`) that don't
/// deserialize `net0` / `net1` / ... etc. Hitting the raw endpoint
/// preserves the indexed-key shape. The `reqwest::Client` carries the
/// PVE auth header from `Config::build_reqwest_client`.
pub async fn fetch_guest_config(
    http: &reqwest::Client,
    base_url: &str,
    node: &str,
    kind: GuestKind,
    vmid: u64,
) -> Result<responses::GuestConfigResponse, ProxmoxError> {
    if node.is_empty() {
        return Err(ProxmoxError::Missing("node"));
    }
    let url = format!(
        "{}/nodes/{}/{}/{}/config",
        base_url.trim_end_matches('/'),
        plugin_toolkit::urlencoding::encode(node),
        kind.as_str(),
        vmid
    );
    let resp = http
        .get(&url)
        .send()
        .await
        .map_err(|e| ProxmoxError::Transport(e.to_string()))?;
    let body = resp
        .text()
        .await
        .map_err(|e| ProxmoxError::Transport(e.to_string()))?;
    serde_json::from_str::<responses::GuestConfigResponse>(&body)
        .map_err(|e| ProxmoxError::Malformed(format!("guest_config: typed parse: {e}")))
}

/// Pull the systemd journal for one node and wrap the generated
/// `Vec<String>` payload into the `responses::JournalResponse` envelope
/// the tool surface returns.
pub async fn fetch_journal(
    client: &generated::Client,
    node: &str,
    q: responses::JournalQuery,
) -> Result<responses::JournalResponse, ProxmoxError> {
    if node.is_empty() {
        return Err(ProxmoxError::Missing("node"));
    }
    let lines = client
        .get_journal_nodes_node_journal(
            node,
            None,
            q.lastentries.map(|n| n as u64),
            q.since,
            None,
            q.until,
        )
        .await
        .map_err(|e| ProxmoxError::Transport(format!("journal: {e}")))?
        .into_inner();
    Ok(responses::JournalResponse { data: lines })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn guest_kind_parses() {
        assert!(matches!(
            "qemu".parse::<GuestKind>().unwrap(),
            GuestKind::Qemu
        ));
        assert!(matches!(
            "vm".parse::<GuestKind>().unwrap(),
            GuestKind::Qemu
        ));
        assert!(matches!(
            "lxc".parse::<GuestKind>().unwrap(),
            GuestKind::Lxc
        ));
        assert!("foo".parse::<GuestKind>().is_err());
    }

    #[test]
    fn action_parses_known_strings() {
        assert!(matches!(
            "start".parse::<ProxmoxAction>().unwrap(),
            ProxmoxAction::Start
        ));
        assert!(matches!(
            "shutdown".parse::<ProxmoxAction>().unwrap(),
            ProxmoxAction::Shutdown
        ));
        assert!("foo".parse::<ProxmoxAction>().is_err());
    }

    #[tokio::test]
    async fn reqwest_client_attaches_pve_auth_header() {
        use wiremock::matchers::{header, method, path};
        use wiremock::{Mock, MockServer, ResponseTemplate};

        _ = rustls::crypto::ring::default_provider().install_default();

        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/probe"))
            .and(header(
                "authorization",
                "PVEAPIToken=user@pve!auto=deadbeef-1111-2222-3333-444444444444",
            ))
            .respond_with(ResponseTemplate::new(200).set_body_string("ok"))
            .mount(&server)
            .await;

        let cfg = Config::new(
            server.uri(),
            "user@pve!auto",
            "deadbeef-1111-2222-3333-444444444444",
        );
        let http = cfg.build_reqwest_client().unwrap();
        let r = http
            .get(format!("{}/probe", server.uri()))
            .send()
            .await
            .unwrap();
        assert_eq!(r.status(), 200);
    }
}
